apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        log
        health
        ready
        kubernetes cluster.local 10.254.0.0/16
        forward . 10.4.7.11
        cache 30
        loop
        reload
        loadbalance
       }
